//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teknik_Servis_Kayit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        public byte M_id { get; set; }
        public string M_Ad { get; set; }
        public string M_Soyad { get; set; }
        public string M_Tel { get; set; }
        public Nullable<short> Tutar { get; set; }
        public string UrunAd { get; set; }
        public string SeriNo { get; set; }
        public string Sikayet { get; set; }
        public string Islem { get; set; }
        public string Islem_Durumu { get; set; }
        public string Odeme_Durumu { get; set; }
    }
}
